# Generated by Django 5.1.4 on 2025-02-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producturl',
            name='url',
            field=models.URLField(max_length=2083, unique=True),
        ),
    ]
